name: Backend CI (Task)

on: 
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Create env file
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> backend-service-nodejs/.env
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> backend-service-nodejs/.env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> backend-service-nodejs/.env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> backend-service-nodejs/.env

      - name: Install dependencies
        working-directory: ./backend-service-nodejs
        run: npm install

      - name: Start DB service
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose --env-file backend-service-nodejs/.env up -d postgres

      - name: Check DB service
        run: |
          docker ps
          docker logs task-db
          
      - name: Run tests
        working-directory: backend-service-nodejs
        run: npm test

      - name: Build Docker image
        run: docker build -t backend-service ./backend-service-nodejs

      - name: Cleanup containers
        if: always()
        run: |
          docker-compose --env-file backend-service-nodejs/.env down -v