name: Backend CI (Task)

on: 
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: ./backend-service-nodejs
        run: npm install

      - name: Start DB service
        run: docker-compose --env-file backend-service-nodejs/.env up

      - name: Run tests
        working-directory: backend-service-nodejs
        run: npm test

      - name: Build Docker image
        run: docker build -t backend-service ./backend-service-nodejs